import Foundation

/// A move generated by the HOST that players must respond to.
struct Move: Codable, Equatable, Identifiable {
    let id: UUID
    let kind: Kind
    let timestamp: Date

    enum Kind: String, Codable, CaseIterable {
        case tapFast    // tap as many times as possible
        case shakeIt    // shake the device
        case holdSteady // keep the device still (reverse — no motion wins)
    }

    /// Human-readable instruction shown to players.
    var instruction: String {
        switch kind {
        case .tapFast:    return "Tap as fast as you can!"
        case .shakeIt:    return "Shake your device!"
        case .holdSteady: return "Hold perfectly still!"
        }
    }

    static func random() -> Move {
        Move(id: UUID(), kind: Kind.allCases.randomElement()!, timestamp: Date())
    }
}

/// Full game state — the HOST is the single source of truth.
struct GameState: Codable, Equatable {
    var scores: [String: Int] = [:]
    var round: Int = 1
    var totalRounds: Int = 5
    var currentMove: Move?
    var timeRemaining: TimeInterval = 10 // per-move time
}

enum GamePhase: Equatable {
    case idle
    case countdown(Int)  // 3-2-1 before round starts
    case playing
    case movePause       // brief pause between moves
    case results
}

/// Actions a player can take in response to a Move.
enum PlayerAction: Codable, Equatable {
    case tap
    case shake
    case steadyScore(Double) // accelerometer stability score (lower = steadier)
}
